[package]
name = "schinken"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]

[dependencies]
wasm-bindgen = "0.2.24"
web-sys = { version = "0.3", features = [ 'Document', 'Element', 'HtmlElement', 'Node', 'NodeList', 'Window', ] }

[workspace]
members = [
    "examples/*",
]

